# Generated by Django 3.2.7 on 2022-03-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='card-image.svg', null=True, upload_to=''),
        ),
    ]
