# Generated by Django 3.2.7 on 2022-03-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20220319_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='placeholder-image.jpg', null=True, upload_to=''),
        ),
    ]
