# Generated by Django 3.2.7 on 2022-04-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productattribute_productattribvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
