# Generated by Django 3.2.7 on 2022-05-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20220428_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='placeholder-image.jpg', null=True, upload_to='products/'),
        ),
    ]
