# Generated by Django 3.2.7 on 2022-05-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='person-circle.svg', null=True, upload_to='profile-pics/'),
        ),
    ]
