# Generated by Django 3.2.7 on 2022-01-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
