# Generated by Django 3.2.7 on 2022-01-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.CharField(choices=[('Downvote', 'Downvote'), ('Upvote', 'Upvote')], max_length=10),
        ),
    ]
