# Generated by Django 3.2.7 on 2021-12-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0005_auto_20211206_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='downvote',
            new_name='downvotes',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='upvote',
            new_name='upvotes',
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.CharField(choices=[('Downvote', 'Downvote'), ('Upvote', 'Upvote')], default='LIKE', max_length=10),
        ),
    ]
