# Generated by Django 3.2.7 on 2022-02-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0005_auto_20220201_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.CharField(choices=[('Upvote', 'Upvote'), ('Downvote', 'Downvote')], max_length=10),
        ),
    ]
