# Generated by Django 3.2.7 on 2022-02-11 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0006_alter_vote_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='review',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
