# Generated by Django 3.2.7 on 2022-02-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0007_auto_20220211_2239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
