# Generated by Django 3.2.7 on 2022-02-27 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0008_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
