# Generated by Django 3.2.7 on 2022-01-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0011_auto_20211224_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.CharField(choices=[('Upvote', 'Upvote'), ('Downvote', 'Downvote')], max_length=10),
        ),
    ]
