# Generated by Django 3.2.7 on 2022-02-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.CharField(choices=[('Downvote', 'Downvote'), ('Upvote', 'Upvote')], max_length=10),
        ),
    ]
