# Generated by Django 3.2.7 on 2022-03-02 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0006_alter_comment_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comments',
            field=models.ManyToManyField(blank=True, default=None, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='review.review'),
        ),
    ]
