# Generated by Django 3.2.7 on 2022-03-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0014_auto_20220319_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.CharField(choices=[('Downvote', 'Downvote'), ('Upvote', 'Upvote')], max_length=10),
        ),
    ]
