# Generated by Django 3.2.7 on 2022-05-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0020_auto_20220509_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_image1',
            field=models.ImageField(blank=True, null=True, upload_to='review-images/'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_image2',
            field=models.ImageField(blank=True, null=True, upload_to='review-images/'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_image3',
            field=models.ImageField(blank=True, null=True, upload_to='review-images/'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.CharField(choices=[('Downvote', 'Downvote'), ('Upvote', 'Upvote')], max_length=10),
        ),
    ]
