# Generated by Django 3.2.7 on 2022-05-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0021_auto_20220528_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.CharField(choices=[('Upvote', 'Upvote'), ('Downvote', 'Downvote')], max_length=10),
        ),
    ]
